# Generated by Django 6.0.1 on 2026-01-11 13:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('issuer', models.CharField(blank=True, max_length=255)),
                ('date', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('credential_url', models.URLField(blank=True, max_length=500)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree', models.CharField(max_length=255)),
                ('institution', models.CharField(max_length=255)),
                ('year', models.CharField(max_length=100)),
                ('grade', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Education',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('company', models.CharField(max_length=255)),
                ('period', models.CharField(help_text="e.g., 'June 2024 - July 2024'", max_length=100)),
                ('description', models.TextField()),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProfileInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(default='Abdullah Noman', max_length=255)),
                ('title', models.CharField(default='Textile Engineer', max_length=255)),
                ('bio', models.TextField(help_text='About me description')),
                ('profile_image', models.URLField(blank=True, max_length=500)),
                ('cv_link', models.URLField(blank=True, max_length=500)),
                ('email', models.EmailField(default='abdnoman001@gmail.com', max_length=254)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('website', models.URLField(blank=True, max_length=500)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('github_url', models.URLField(blank=True, max_length=500)),
                ('linkedin_url', models.URLField(blank=True, max_length=500)),
                ('twitter_url', models.URLField(blank=True, max_length=500)),
                ('facebook_url', models.URLField(blank=True, max_length=500)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Profile Information',
                'verbose_name_plural': 'Profile Information',
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('technical', 'Technical Skills'), ('specialized', 'Specialized Skills'), ('software', 'Software & Tools'), ('other', 'Other')], default='technical', max_length=50)),
                ('proficiency', models.IntegerField(default=50, help_text='Proficiency level (0-100)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['category', 'order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='core_contac_created_25856d_idx'), models.Index(fields=['is_read'], name='core_contac_is_read_c89f0a_idx')],
            },
        ),
    ]
