# Generated by Django 6.0.1 on 2026-01-12 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profileinfo',
            name='about',
            field=models.TextField(blank=True, help_text='Detailed about me description'),
        ),
        migrations.AddField(
            model_name='profileinfo',
            name='achievements',
            field=models.JSONField(blank=True, default=list, help_text='List of achievements'),
        ),
        migrations.AlterField(
            model_name='profileinfo',
            name='bio',
            field=models.TextField(help_text='Short bio/tagline'),
        ),
    ]
